/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Form;

import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
import Perbankan.Nasabah;
import Perbankan.Bank;
import Perbankan.Tabungan;
import Form.TarikTunai;
import Form.SetorTunai;

/**
 *
 * @author ASUS
 */
public class BankForm extends javax.swing.JFrame {

    DefaultTableModel model;
    public int rowIndex;
    private Bank bank;

    public BankForm() {
        initComponents();
        bank = new Bank();
        tampilData();
    }

    public void tampilData() {
        int jumlahNasabah = bank.getJumlahNasabah();
        int noUrut = 1;
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("No.");
        model.addColumn("Nama Awal");
        model.addColumn("Nama Akhir");
        model.addColumn("Saldo");

        model.setRowCount(0);

        for (int i = 0; i < jumlahNasabah; i++) {
            if (bank.getNasabah(i).getNamaAwal() == "") {
                continue;
            }
            model.addRow(new Object[] {
                    noUrut++,
                    bank.getNasabah(i).getNamaAwal(),
                    bank.getNasabah(i).getNamaAkhir(),
                    bank.getNasabah(i).getTabungan().getSaldo(), });
        }

        tabel.setModel(model);
    }

    public void reset() {
        Namaawal.setText(null);
        Namaakhir.setText(null);
        saldo.setText(null);
    }

    private Nasabah pilihNasabah() {
        int selectedRow = getselectedRow();
        String namaAwal = tabel.getValueAt(selectedRow, 1).toString();
        String namaAkhir = tabel.getValueAt(selectedRow, 2).toString();
        int indexNasabah = bank.getIndexNasabah(namaAwal, namaAkhir);
        return bank.getNasabah(indexNasabah);
    }

    public int getselectedRow() {
        return tabel.getSelectedRow();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Namaawal = new javax.swing.JTextField();
        Namaakhir = new javax.swing.JTextField();
        saldo = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabel = new javax.swing.JTable();
        jButton4 = new javax.swing.JButton();
        titleApk = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel3.setFont(new java.awt.Font("CorpidOffice", 0, 12)); // NOI18N
        jLabel3.setText("Nama Awal");

        jLabel4.setFont(new java.awt.Font("CorpidOffice", 0, 12)); // NOI18N
        jLabel4.setText("Nama Akhir");

        jLabel5.setFont(new java.awt.Font("CorpidOffice", 0, 12)); // NOI18N
        jLabel5.setText("Saldo");

        Namaawal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NamaawalActionPerformed(evt);
            }
        });

        Namaakhir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NamaakhirActionPerformed(evt);
            }
        });

        saldo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saldoActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(19, 138, 51));
        jButton1.setFont(new java.awt.Font("CorpidOffice", 0, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Simpan");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(163, 8, 0));
        jButton2.setFont(new java.awt.Font("CorpidOffice", 0, 12)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Hapus");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(138, 131, 0));
        jButton3.setFont(new java.awt.Font("CorpidOffice", 0, 12)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Clear");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        tabel.setBackground(new java.awt.Color(255, 255, 255));
        tabel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "No", "Nama Awal", "Nama Akhir", "Saldo"
            }
        ));
        tabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tabel);

        jButton4.setBackground(new java.awt.Color(51, 81, 189));
        jButton4.setFont(new java.awt.Font("CorpidOffice", 0, 12)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Setor");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        titleApk.setFont(new java.awt.Font("CorpidOffice", 1, 36)); // NOI18N
        titleApk.setText("Aplikasi Perbankan");

        jButton5.setBackground(new java.awt.Color(64, 64, 64));
        jButton5.setFont(new java.awt.Font("CorpidOffice", 0, 12)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("Keluar");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setBackground(new java.awt.Color(51, 81, 189));
        jButton6.setFont(new java.awt.Font("CorpidOffice", 0, 12)); // NOI18N
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setText("Tarik");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Namaakhir)
                                    .addComponent(Namaawal)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(21, 21, 21)
                                        .addComponent(jButton1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButton2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButton3)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(16, 16, 16)
                                        .addComponent(saldo)))))
                        .addGap(23, 23, 23))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(titleApk, javax.swing.GroupLayout.PREFERRED_SIZE, 393, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(75, 75, 75)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 458, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton4)
                            .addComponent(jButton6)
                            .addComponent(jButton5))
                        .addGap(0, 32, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titleApk)
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(Namaawal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(Namaakhir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(saldo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton4)
                        .addGap(18, 18, 18)
                        .addComponent(jButton6)
                        .addGap(18, 18, 18)
                        .addComponent(jButton5))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE))
                .addGap(12, 12, 12))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tabelMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_tabelMouseClicked
        DefaultTableModel model = (DefaultTableModel) tabel.getModel();
        int selectedRow = tabel.getSelectedRow();
        Nasabah nasabah = pilihNasabah();
        Namaawal.setText(nasabah.getNamaAwal());
        Namaakhir.setText(nasabah.getNamaAkhir());
        int Saldo = nasabah.getTabungan().getSaldo();
        saldo.setText(Integer.toString(Saldo));
        saldo.setEditable(true);
        jButton1.setText("simpan");
    }// GEN-LAST:event_tabelMouseClicked

    
    private void NamaawalActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_NamaawalActionPerformed
        // TODO add your handling code here:

    }// GEN-LAST:event_NamaawalActionPerformed

    private void NamaakhirActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_NamaakhirActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_NamaakhirActionPerformed

    private void saldoActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_saldoActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_saldoActionPerformed
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton1ActionPerformed
        int jumlahNasabah = bank.getJumlahNasabah();
        String NamaAwal = Namaawal.getText();
        String NamaAkhir = Namaakhir.getText();
        int Saldo = 0;
        try {
            Saldo = Integer.parseInt(saldo.getText());
        } catch (NumberFormatException e) {
            // Penanganan jika input Saldo bukan angka
            JOptionPane.showMessageDialog(null, "Data tidak valid");
            return;
        }

        if (NamaAwal.trim().equals("") || NamaAkhir.trim().equals("") || Saldo == 0) {
            JOptionPane.showMessageDialog(null, "Data belum lengkap");
        } else {
            if (jButton1.getText() == "simpan") {
                Nasabah nasabah = pilihNasabah();
                nasabah.setNamaAwal(Namaawal.getText());
                nasabah.setNamaAkhir(Namaakhir.getText());

            } else {
                bank.tambahNasabah(NamaAwal, NamaAkhir);
                bank.getNasabah(jumlahNasabah).setTabungan(new Tabungan(Saldo));
            }
            rowIndex++;
            // model.addRow(new Object[]{rowIndex,norek, NamaAwal, NamaAkhir, Saldo});
            reset();
            tampilData();
        }
    }// GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton2ActionPerformed
        if (Namaawal.getText().equals("")
                || Namaakhir.getText().equals("")
                || saldo.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Silahkan pilih data yang ingin dihapus!", "Validasi Data",
                    JOptionPane.INFORMATION_MESSAGE);
        } else {
            int jawab = JOptionPane.showConfirmDialog(null, "Data ini akan dihapus ?", "Konfirmasi",
                    JOptionPane.YES_NO_OPTION);
            if (jawab == 0) {
                Nasabah nasabah = pilihNasabah();
                nasabah.setNamaAwal("");
                nasabah.setNamaAkhir("");

                reset();
                tampilData();
            }

        }
    }// GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton3ActionPerformed
        saldo.setEditable(true);
        reset();
    }// GEN-LAST:event_jButton3ActionPerformed

    
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton4ActionPerformed

        int selectedRow = getselectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Pilih nasabah terlebih dahulu");
            return;
        }
        String namaAwal = tabel.getValueAt(selectedRow, 1).toString();
        String namaAkhir = tabel.getValueAt(selectedRow, 2).toString();
        int indexNasabah = bank.getIndexNasabah(namaAwal, namaAkhir);
        SetorTunai setor = new SetorTunai(indexNasabah, bank, this); // Gantilah "JFrame2" dengan nama JFrame
                                                                            // kedua Anda

        setor.setVisible(true); // Menutup JFrame pertama jika diperlukan
        this.setVisible(false);

    }// GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton5ActionPerformed
        this.dispose();
    }// GEN-LAST:event_jButton5ActionPerformed
    
    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        int selectedRow = getselectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Pilih nasabah terlebih dahulu");
            return;
        }
        String namaAwal = tabel.getValueAt(selectedRow, 1).toString();
        String namaAkhir = tabel.getValueAt(selectedRow, 2).toString();
        int indexNasabah = bank.getIndexNasabah(namaAwal, namaAkhir);
        TarikTunai setor = new TarikTunai(indexNasabah, bank, this);
        setor.setVisible(true); // Menutup JFrame pertama jika diperlukan
        this.setVisible(false);
    }//GEN-LAST:event_jButton6ActionPerformed

    

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BankForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BankForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BankForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BankForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new BankForm().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Namaakhir;
    private javax.swing.JTextField Namaawal;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField saldo;
    private javax.swing.JTable tabel;
    private javax.swing.JLabel titleApk;
    // End of variables declaration//GEN-END:variables
}